### ISSUE TITLE
Mooi strak en overzichtelijk

### ISSUE THREAD

**Issue by erwinhenraat** [221boy221/tower-defense#1]
``` c
Application.LoadLevel("GameOver"); 
```

Bestand: https://github.com/221boy221/tower-defense/blob/master/tower-defense/Assets/Scripts/Player.cs

Goede compacte functions. Heel erg overzichtelijk.

**Comment by 221boy221** [comment]
Thanks, En goed toegankelijk vanuit andere classes, zonder ze static te maken.
