### ISSUE TITLE
Onnodige opvulling

### ISSUE THREAD

**Issue by erwinhenraat** [221boy221/tower-defense#5]
``` c
  if (_spawn) { 
```

Bestand: https://github.com/221boy221/tower-defense/blob/master/tower-defense/Assets/Scripts/Enemies/SpawnScript.cs

Deze boolean is altijd true, dus wat is hier het nut van? 

Maak je code niet onnodig complex door dit soort toevoegingen. Code uitschakelen kun je ook heel snel met /\* */

**Comment by 221boy221** [comment]
Fixed.
