### ISSUE TITLE
plaatsen van classes in passende package

### ISSUE THREAD

**Issue by erwinhenraat** [221boy221/tower-defense#8]
Bestand: https://github.com/221boy221/tower-defense/tree/master/tower-defense/Assets/Scripts/Towers

in je enemies package staat nu ook je spawnscript en in de towers ook je bullets.

wellicht zijn hiervoor nog duidelijkere plekken te bedenken?!

**Comment by 221boy221** [comment]
Dat is waar, de bullet zou ook zo maar van een enemy afkomstig kunnen zijn, heb 't nu onder Ammo neer gezet.
